-- Importing other config files --
require("Hyprland/Animation")
require("Hyprland/Appearance/Blur")
require("Hyprland/Appearance/Colours")
require("Hyprland/Appearance/General")
require("Hyprland/Appearance/Shadow")
require("Hyprland/Window/Rules")
require("Hyprland/Autostart")
require("Hyprland/Configs")
require("Hyprland/Env")
require("Hyprland/Input")
require("Hyprland/Keybinds")
require("Hyprland/Layout")
require("Hyprland/Monitors")