hl.on("hyprland.start", function () 
   hl.exec_cmd("code")
   hl.exec_cmd("firefox")
   hl.exec_cmd("awww-daemon &")
   hl.exec_cmd("pipewire")
   hl.exec_cmd("wireplumber")
   hl.exec_cmd("pipewire-pulse")
end)